# Generated by Django 4.1.4 on 2023-01-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryname', models.CharField(max_length=64, verbose_name='工厂名称')),
                ('adress', models.CharField(max_length=128, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='stockbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockbasename', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('adress', models.CharField(max_length=128, verbose_name='仓库地址')),
                ('maxnumber', models.SmallIntegerField(verbose_name='容纳数量')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, 'man'), (2, 'women')], verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=3, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(max_length=64, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='rawstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, verbose_name='原料')),
                ('remark', models.CharField(default=None, max_length=32, verbose_name='备注')),
                ('number', models.SmallIntegerField(default=None, verbose_name='编号')),
                ('amount', models.SmallIntegerField(default=None, verbose_name='数量')),
                ('price', models.SmallIntegerField(default=None, verbose_name='单价')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64, verbose_name='产品名称')),
                ('remark', models.CharField(default=None, max_length=32, null=True, verbose_name='备注')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.industry', verbose_name='工厂')),
                ('stockbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.stockbase', verbose_name='仓库')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.rawstock', verbose_name='原材料')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员')),
            ],
        ),
        migrations.CreateModel(
            name='LYKJSYS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zijin_L', models.SmallIntegerField(default=0, verbose_name='资金数量')),
                ('time_L', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('number_L', models.CharField(blank=True, max_length=64, null=True, verbose_name='编号')),
                ('type_L', models.SmallIntegerField(choices=[(1, '借'), (2, '贷'), (3, '待处理')], verbose_name='借/贷')),
                ('note_L', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('admin_L', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员')),
                ('kemu_L', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.account_t', verbose_name='会计科目')),
            ],
        ),
    ]
