# Generated by Django 4.1 on 2022-10-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rawstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='原料')),
                ('remark', models.CharField(max_length=32, verbose_name='备注')),
                ('number', models.SmallIntegerField(max_length=8, verbose_name='编号')),
                ('amount', models.SmallIntegerField(max_length=8, verbose_name='数量')),
                ('price', models.SmallIntegerField(max_length=8, verbose_name='单价')),
            ],
        ),
    ]
