# Generated by Django 4.1 on 2022-10-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_rawstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstock',
            name='amount',
            field=models.SmallIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='number',
            field=models.SmallIntegerField(verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='price',
            field=models.SmallIntegerField(verbose_name='单价'),
        ),
    ]
