# Generated by Django 4.1 on 2022-10-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0003_alter_rawstock_amount_alter_rawstock_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstock',
            name='amount',
            field=models.SmallIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='name',
            field=models.CharField(default=0, max_length=32, verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='remark',
            field=models.CharField(default=0, max_length=32, verbose_name='备注'),
        ),
    ]
