# Generated by Django 4.1 on 2022-10-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstock',
            name='name',
            field=models.CharField(default=None, max_length=32, verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='remark',
            field=models.CharField(default=None, max_length=32, verbose_name='备注'),
        ),
    ]
