# Generated by Django 4.1 on 2022-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0008_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(max_length=64, verbose_name='备注'),
        ),
    ]
