# Generated by Django 4.1 on 2022-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0014_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64, verbose_name='产品名称')),
                ('remark', models.CharField(default=None, max_length=32, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='stockbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockbase', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('remark', models.CharField(default=None, max_length=32, verbose_name='备注')),
                ('product', models.ManyToManyField(max_length=64, to='app001.product', verbose_name='仓库关联的产品')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=64, verbose_name='原材料名称')),
                ('remark', models.CharField(default=None, max_length=32, verbose_name='备注')),
                ('product', models.ManyToManyField(max_length=64, to='app001.product', verbose_name='关联的产品')),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=64, verbose_name='工厂名称')),
                ('remark', models.CharField(default=None, max_length=32, verbose_name='备注')),
                ('product', models.ManyToManyField(max_length=64, to='app001.product', verbose_name='工厂关联的产品')),
            ],
        ),
    ]
