# Generated by Django 4.1 on 2022-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0015_product_stockbase_material_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='kind',
            field=models.CharField(default=0, max_length=16, verbose_name='种类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.CharField(default=0, max_length=16, verbose_name='供应商'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
    ]
