# Generated by Django 4.1 on 2022-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0016_material_kind_material_supplier_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material',
        ),
        migrations.RemoveField(
            model_name='stockbase',
            name='stockbase',
        ),
        migrations.AddField(
            model_name='industry',
            name='industryname',
            field=models.CharField(default=0, max_length=64, verbose_name='工厂名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='materialname',
            field=models.CharField(default=0, max_length=64, verbose_name='原材料名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbase',
            name='stockbasename',
            field=models.CharField(default=0, max_length=64, verbose_name='仓库名称'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='alltogetherproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ManyToManyField(to='app001.industry')),
                ('material', models.ManyToManyField(to='app001.material')),
                ('product', models.ManyToManyField(to='app001.product')),
                ('stockbase', models.ManyToManyField(to='app001.stockbase')),
            ],
        ),
    ]
