# Generated by Django 4.1 on 2022-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0017_remove_industry_industry_remove_material_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='product',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='stockbase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockbase',
            name='remark',
        ),
        migrations.AddField(
            model_name='product',
            name='industry',
            field=models.ManyToManyField(to='app001.industry'),
        ),
        migrations.AddField(
            model_name='product',
            name='stockbase',
            field=models.ManyToManyField(to='app001.stockbase'),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(to='app001.rawstock'),
        ),
        migrations.DeleteModel(
            name='alltogetherproduct',
        ),
        migrations.DeleteModel(
            name='material',
        ),
    ]
