# Generated by Django 4.1 on 2022-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industryname',
            field=models.CharField(max_length=64, unique=True, verbose_name='工厂名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='rawstock',
            name='name',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='stockbasename',
            field=models.CharField(max_length=64, unique=True, verbose_name='仓库名称'),
        ),
    ]
