# Generated by Django 4.1 on 2022-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='industry',
            field=models.ManyToManyField(related_query_name='indus', to='app001.industry'),
        ),
    ]
