# Generated by Django 4.1 on 2022-11-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0026_industry_adress_stockbase_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.industry', verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stockbase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.stockbase', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.rawstock', verbose_name='原材料'),
        ),
    ]
