# Generated by Django 4.1 on 2022-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0027_alter_order_status_alter_product_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='备注'),
        ),
    ]
