# Generated by Django 4.1 on 2022-11-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0028_alter_order_status_alter_product_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbase',
            name='maxnumber',
            field=models.SmallIntegerField(default=123, max_length=128, verbose_name='容纳数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='adress',
            field=models.CharField(max_length=128, verbose_name='仓库地址'),
        ),
    ]
