# Generated by Django 4.1.4 on 2023-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0029_product_admin_stockbase_maxnumber_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='maxnumber',
            field=models.SmallIntegerField(verbose_name='容纳数量'),
        ),
    ]
