# Generated by Django 4.1.4 on 2023-01-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0030_alter_order_status_alter_stockbase_maxnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='LYKJSYS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zijin_L', models.SmallIntegerField(default=0, verbose_name='资金数量')),
                ('time_L', models.TimeField(verbose_name='时间')),
                ('number_L', models.CharField(max_length=64, verbose_name='编号')),
                ('type_L', models.SmallIntegerField(choices=[(1, '借'), (2, '贷'), (3, '待处理')], verbose_name='借/贷')),
                ('note', models.CharField(default=None, max_length=64, verbose_name='备注')),
                ('admin_L', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.admin', verbose_name='管理员')),
                ('kemu_L', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.account_t', verbose_name='会计科目')),
            ],
        ),
    ]
