# Generated by Django 4.1.4 on 2023-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0031_alter_order_status_lykjsys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lykjsys',
            old_name='note',
            new_name='note_L',
        ),
    ]
