# Generated by Django 4.1.4 on 2023-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0034_alter_lykjsys_note_l_alter_lykjsys_number_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lykjsys',
            name='time_L',
            field=models.TimeField(blank=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
    ]
