# Generated by Django 4.1.4 on 2023-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0036_alter_lykjsys_time_l_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lykjsys',
            name='time_L',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
